name: todos
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: "> 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.13.2
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  uuid: ^2.1.0

dev_dependencies:
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

dependency_overrides:
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  riverpod:
    path: ../../packages/riverpod

flutter:
  uses-material-design: true
