name: hooks_riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and testable.
version: 0.6.0
homepage: https://riverpod.dev

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_riverpod: ^0.6.0
  riverpod: ^0.6.0
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.11.0 <2.0.0"
  collection: ^1.14.12
  state_notifier: ">= 0.5.0 <1.0.0"

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
