name: flutter_riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and being testable.
version: 0.2.0
homepage: https://riverpod.dev
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">= 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.12
  riverpod: ^0.2.0
  state_notifier: ^0.5.0

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
