name: riverpod_cli
description: A command line tool for Riverpod
version: 0.0.1
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.5.0
  codemod: ^0.2.0
  glob: ^1.2.0

dev_dependencies:
  test: any

executables:
  riverpod: riverpod_cli
