name: firebase_auth_flutter_ddd
description: Firebase authentication example with Hooks Riverpod and Freezed following Flutter DDD architecture



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
#  flutter_riverpod:
#    path: ../../packages/flutter_riverpod
  freezed_annotation: ^0.14.2
  hooks_riverpod:
    path: ../../packages/hooks_riverpod

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
